# Generated by Django 5.1.4 on 2025-01-05 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_borrowedbook'),
        ('library', '0003_remove_library_latitude_remove_library_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available',
        ),
        migrations.RemoveField(
            model_name='book',
            name='library',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='book',
        ),
        migrations.CreateModel(
            name='BookInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='book.book')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='library.librarybranch')),
            ],
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='book_inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.bookinventory'),
        ),
    ]
