# Generated by Django 5.1.4 on 2025-01-06 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_available_remove_book_library_and_more'),
        ('library', '0003_remove_library_latitude_remove_library_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='book_inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.bookinventory'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bookinventory',
            unique_together={('book', 'branch')},
        ),
    ]
